postPath = "./post/"

[host]
server = "10.0.2.15"
port = 8080

[db]
enable = false
dbtype = "mongodb"
dbname = "mytest"

[filecfg]
autorefresh = true
refreshfreq = 5    # the frequency of refreshing the fold which is postPath(unit:second)
includefile  = ["md","cm"]    # md means markdown files, cm means comment files
usefilepool = true

[logcfg]
enable        = true
showinconsole = true
logpath       = "./log/"

[pagecfg]
maxitemperpage = 5    # the max number of each page show

[website]
webtitle = "Welcome"
